config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :activities, only: [:index, :show]
  resources :orders, only: [:create, :show, :index]
  root to: "activities#index"
end

app/models/activity.rb
class Activity < ApplicationRecord

  def self.all_active_activities_sorted
    all.where("date > ?", Time.now).where("max_attendies > current_attendies").order("date")
  end

  def available_tickets
    max_attendies - current_attendies
  end

  def date_formatted
    date.strftime("%d.%m.%Y %H:%M %p")
  end

  def price_with_text
    "#{price}$ per ticket"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  # relations
  belongs_to :activity
  belongs_to :user
  # validations
  validates :tickets, numericality: { only_integer: true }
  validate :validate_number_of_tickets
  # callbacks
  before_save :set_total_price
  after_save :update_current_attendies


  def validate_number_of_tickets
    errors.add(:tickets, "There are no #{tickets} tickets available, tickets available: #{activity.available_tickets}") if activity.available_tickets < tickets
  end

  def set_total_price
    # total price may be different from tickets * activity.price when adding discounts in the future
    self.total_price = tickets * activity.price
  end

  def update_current_attendies
    new_attendies = activity.current_attendies + tickets
    activity.update_attribute(:current_attendies, new_attendies)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all_active_activities_sorted
  end

  def show
    @activity = Activity.all_active_activities_sorted.find_by_id(params[:id])
    if @activity == nil
      flash[:alert] = "There is no such activity."
      redirect_to :root
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/helpers/activities_helper.rb
module ActivitiesHelper
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/orders_helper.rb
module OrdersHelper
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    permitted = params.require(:order).permit(:tickets, :activity_id)
    @order = Order.new(permitted)
    @order.user = current_user
    @activity = @order.activity

    if @order.save
      redirect_to @order
    else
      redirect_to @activity
    end
  end

  def show
    @order = current_user.orders.find_by_id(params[:id])
    if @order == nil
      flash[:alert] = "There is no such order."
      redirect_to :root
    else
      @activity = @order.activity
    end

  end

  def index
    @orders = current_user.orders
  end

end

app/views/activities/index.html.erb
<div class="row">
  <% if @activities.size == 0 %>
    <h3>There are no activities</h3>
  <% else %>

    <% @activities.each do |activity| %>

    <%= link_to(activity_path(activity), class: "activity col-xs-12 col-sm-6 col-lg-4") do %>
        <table>
          <tr><td><h3><%= activity.title %></h3></td></tr>
          <tr><td><div><%= activity.date_formatted %></div></td></tr>
          <tr><td><div><%= activity.price_with_text %></div></td></tr>
        </table>
      <% end %>

    <% end %>

  <% end %>
</div>

app/views/activities/show.html.erb
<div class="activity-page">

<div class="left-section white-bg col-xs-12 col-sm-6">
  <table>
    <tr><td><h3><%= @activity.title %></h3></td></tr>
    <tr><td>Hosted by <%= @activity.owner %></td></tr>
    <tr><td><p><%= @activity.desc %></p></td></tr>
  </table>
</div>

<div class="right-section col-xs-12 col-sm-4">
  <%= form_for Order.new do |f| %>
  <%= f.hidden_field(:activity_id, value: @activity.id) %>
  <table>
    <tr><td>
      <div class="right-section-inner">

        <h4><%= @activity.date_formatted %></h4>
        <div><%= @activity.price_with_text %></div>
        <div>
          How many tickets?
          <br />
          <%= f.number_field(:tickets, in: 1..@activity.available_tickets, step: 1, value: 1, class: "form-control") %>
        </div>
        <%= f.submit("Book Now!", class: "book-now") %>
        
      </div>
    </td></tr>
  </table>

  <% end %>
</div>


</div>

app/views/layouts/_nav.html.erb
<div class="links">
  <%= link_to "My Orders", orders_path %>
  <%= link_to "Activities", activities_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funzing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="top-nav container-fluid">
      <!-- top nav -->
      <a href="/">
        <div class="logo">
          Mini Funzing
        </div>
      </a>
      <div class="user-buttons">
        <%= link_to "Login", user_session_path %>
        /
        <%= link_to "Register", new_user_registration_path %>
        /
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    </div>
    <%= render partial: "layouts/nav" if user_signed_in? %>
    <div class="alerts container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="main container-fluid">
      <!-- main content -->
      <%= yield %>
    </div>

  </body>
</html>

app/views/orders/index.html.erb
<div class="col-xs-12 col-sm-6">

  <table>
    <tr><td>
      <h3>My Orders</h3>
    </td></tr>

    <% if @orders.size == 0 %>
      <tr><td>There are no orders yet.</td></tr>
    <% else %>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to "#Order #{order.id} - #{order.activity.title}", order_path(order) %>
          </td>
        </tr>
      <% end %>
    <% end %>
    
  </table>

</div>

app/views/orders/show.html.erb
<div class="col-xs-12 col-sm-8">

  <table>
    <tr><td>
      <h4># Order <%= @order.id %></h4>
      <h3><%= @activity.title %></h3>
    </td></tr>
    <tr><td>
      <span>Hosted by <%= @activity.owner %></span>
    </td></tr>
    <tr><td>
      <h5><%= @activity.date_formatted %></h5>
      <p><%= @order.tickets %> Tickets</p>
      <p>Total price: <%= @order.total_price %>$</p>
    </td></tr>

  </table>



</div>